apiVersion: v1
kind: Pod
metadata:
  name: web-podantiaffinity
  namespace: place-ops
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - wrong-app
            topologyKey: kubernetes.io/hostname
  containers:
    - name: web
      image: nginx:1.25
