apiVersion: v1
kind: Namespace
metadata:
  name: store-ops
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: store-replicas
  namespace: store-ops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
