apiVersion: v1
kind: Pod
metadata:
  name: web-declarative
  namespace: ckad-lab
  labels:
    app: web
spec:
  containers:
    name: nginx
    image: nginx:1.27-alpine
    ports:
      - containerPort: 80
