apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-blue
  namespace: retail-ops
  labels:
    app: checkout
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
      version: blue
  template:
    metadata:
      labels:
        app: checkout
        version: blue
    spec:
      containers:
        - name: checkout
          image: nginx:1.25
          ports:
            - containerPort: 80
